# ============================================================
# 02. Prepare sample metadata and run phosphosite-specific DE/FC analysis
#
# This script is adapted for phosphoproteomics data generated by:
#   01_build_phosphosite_matrix_from_diann.R
#
# Key idea:
#   Your previous DE scripts were mainly designed for protein/gene-level matrices.
#   For phosphoproteomics, a single gene/protein can have many modified peptides
#   or sites, so we must preserve a complete feature ID such as:
#     Protein.Id | Genes | Residue.Both | Modified.Sequence
#
# Therefore, this script DOES NOT strip feature IDs by underscore and DOES NOT
# collapse multiple phosphosites into one gene symbol.
#
# Main inputs:
#   final_mat      : output from prepare_phosphosite_matrix(); rows are phospho features
#   sample_cols    : sample columns from prepare_phosphosite_matrix()
#   sampleinfo.xlsx: contains sample_id / sample_name bridge
#   samplegroup.xlsx: contains sample_name / group information
#   compare_list.xlsx: optional pairwise comparison table
#
# Main outputs:
#   sample_metadata_clean.csv
#   sample_match_check.csv
#   phosphosite_expr_log2*.csv
#   pairwise DE/FC result tables and plots
# ============================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(stringr)
  library(readxl)
  library(limma)
})

# ------------------------------------------------------------
# 0. Small utilities
# ------------------------------------------------------------
.clean_text <- function(x, remove_all_spaces = TRUE) {
  x <- as.character(x)
  x <- trimws(x)
  if (remove_all_spaces) {
    x <- gsub(" ", "", x)
  }
  x
}

.safe_slug <- function(x) {
  x <- as.character(x)
  x <- gsub("[[:space:]]+", "_", x)
  x <- gsub("[/\\\\:;\\*\\?\"<>\\|]", "_", x)
  x <- gsub("\\+", "plus", x)
  x <- gsub("[^[:alnum:]_\\-\\.]", "_", x)
  x <- gsub("_+", "_", x)
  x <- gsub("^_|_$", "", x)
  x
}

.safe_dir_create <- function(path) {
  if (!is.null(path) && nzchar(path)) {
    dir.create(path, recursive = TRUE, showWarnings = FALSE)
  }
}

.scale_rows <- function(mat) {
  row_mean <- rowMeans(mat, na.rm = TRUE)
  row_sd <- apply(mat, 1, stats::sd, na.rm = TRUE)
  row_sd[is.na(row_sd) | row_sd == 0] <- 1
  out <- sweep(mat, 1, row_mean, FUN = "-")
  out <- sweep(out, 1, row_sd, FUN = "/")
  out[!is.finite(out)] <- 0
  out
}

# ------------------------------------------------------------
# 1. Prepare sample metadata
# ------------------------------------------------------------
prepare_phospho_sample_metadata <- function(sampleinfo_file,
                                            samplegroup_file = NULL,
                                            samplegroup_skip = 10,
                                            sample_id_col = "样品编号",
                                            sample_name_col = "样品信息",
                                            samplegroup_cols = c("*样品名称", "*管上名称", "*样品类型", "*样品来源", "样本分组"),
                                            unmatched_group = "ALL",
                                            remove_all_spaces = TRUE,
                                            out_dir = NULL) {
  sample_info <- readxl::read_xlsx(sampleinfo_file) %>%
    as.data.frame(check.names = FALSE)

  if (!sample_id_col %in% names(sample_info)) {
    stop("sampleinfo 缺少样品编号列: ", sample_id_col)
  }
  if (!sample_name_col %in% names(sample_info)) {
    stop("sampleinfo 缺少样品信息列: ", sample_name_col)
  }

  sample_info <- sample_info %>%
    mutate(
      sample_id = .clean_text(.data[[sample_id_col]], remove_all_spaces),
      sample_name = .clean_text(.data[[sample_name_col]], remove_all_spaces)
    )

  if (!is.null(samplegroup_file)) {
    sample_group_raw <- readxl::read_xlsx(
      path = samplegroup_file,
      skip = samplegroup_skip,
      .name_repair = "minimal"
    ) %>%
      as.data.frame(check.names = FALSE)

    missing_cols <- setdiff(samplegroup_cols, names(sample_group_raw))
    if (length(missing_cols) > 0) {
      stop("samplegroup 缺少这些列: ", paste(missing_cols, collapse = ", "))
    }

    sample_group <- sample_group_raw %>%
      select(all_of(samplegroup_cols))

    # Default mapping:
    #   *样品名称 -> original_sample_name
    #   *管上名称 -> sample_name
    #   *样品类型 -> sample_type
    #   *样品来源 -> sample_source
    #   样本分组 -> group
    names(sample_group) <- c("original_sample_name", "sample_name", "sample_type", "sample_source", "group")

    sample_group <- sample_group %>%
      mutate(
        sample_name = .clean_text(sample_name, remove_all_spaces),
        group = .clean_text(group, remove_all_spaces)
      )

    sample_metadata <- sample_info %>%
      left_join(sample_group, by = "sample_name")
  } else {
    sample_metadata <- sample_info
    if (!"group" %in% names(sample_metadata)) {
      sample_metadata$group <- unmatched_group
    }
    if (!"original_sample_name" %in% names(sample_metadata)) sample_metadata$original_sample_name <- NA_character_
    if (!"sample_type" %in% names(sample_metadata)) sample_metadata$sample_type <- NA_character_
    if (!"sample_source" %in% names(sample_metadata)) sample_metadata$sample_source <- NA_character_
  }

  sample_metadata <- sample_metadata %>%
    mutate(
      group = ifelse(is.na(group) | group == "", unmatched_group, group),
      sample_id = as.character(sample_id),
      sample_name = as.character(sample_name)
    ) %>%
    distinct(sample_id, .keep_all = TRUE)

  first_cols <- intersect(
    c("sample_id", "sample_name", "group", "original_sample_name", "sample_type", "sample_source"),
    names(sample_metadata)
  )
  sample_metadata <- sample_metadata %>%
    select(all_of(first_cols), everything())

  if (!is.null(out_dir)) {
    .safe_dir_create(out_dir)
    write.csv(sample_metadata, file.path(out_dir, "sample_metadata_clean.csv"), row.names = FALSE)
  }

  sample_metadata
}

# ------------------------------------------------------------
# 2. Align metadata to quantitative matrix columns
# ------------------------------------------------------------
align_phospho_sample_metadata <- function(sample_metadata,
                                          sample_cols,
                                          out_dir = NULL,
                                          stop_if_unmatched = TRUE) {
  if (!all(c("sample_id", "sample_name", "group") %in% names(sample_metadata))) {
    stop("sample_metadata 必须包含 sample_id, sample_name, group 三列。")
  }

  sample_cols <- as.character(sample_cols)
  sample_metadata$sample_id <- as.character(sample_metadata$sample_id)

  match_check <- tibble(sample_id = union(sample_cols, sample_metadata$sample_id)) %>%
    mutate(
      in_matrix = sample_id %in% sample_cols,
      in_metadata = sample_id %in% sample_metadata$sample_id
    ) %>%
    left_join(sample_metadata %>% select(sample_id, sample_name, group), by = "sample_id")

  if (!is.null(out_dir)) {
    .safe_dir_create(out_dir)
    write.csv(match_check, file.path(out_dir, "sample_match_check.csv"), row.names = FALSE)
  }

  missing_in_metadata <- setdiff(sample_cols, sample_metadata$sample_id)
  missing_in_matrix <- setdiff(sample_metadata$sample_id, sample_cols)

  if (stop_if_unmatched && length(missing_in_metadata) > 0) {
    stop("这些矩阵样本列在 sample_metadata$sample_id 中找不到: ",
         paste(missing_in_metadata, collapse = ", "))
  }

  if (length(missing_in_matrix) > 0) {
    warning("这些 metadata 样本不在矩阵列中，将忽略: ", paste(missing_in_matrix, collapse = ", "))
  }

  sample_metadata_aligned <- sample_metadata %>%
    filter(sample_id %in% sample_cols) %>%
    mutate(.sample_order = match(sample_id, sample_cols)) %>%
    arrange(.sample_order) %>%
    select(-.sample_order)

  if (!identical(sample_metadata_aligned$sample_id, sample_cols)) {
    stop("sample_metadata 不能按 sample_cols 完全对齐，请检查 sample_match_check.csv。")
  }

  rownames(sample_metadata_aligned) <- sample_metadata_aligned$sample_id

  if (!is.null(out_dir)) {
    write.csv(sample_metadata_aligned, file.path(out_dir, "sample_metadata_aligned.csv"), row.names = FALSE)
  }

  sample_metadata_aligned
}

# ------------------------------------------------------------
# 3. Build phosphosite / modified phosphopeptide expression matrix
# ------------------------------------------------------------
make_phosphosite_expr_matrix <- function(final_mat,
                                         sample_cols,
                                         out_dir = NULL,
                                         feature_id_cols = c("Protein.Id", "Genes", "Residue.Both", "Modified.Sequence"),
                                         log2_transform = TRUE,
                                         add1 = 1,
                                         median_scaling = TRUE,
                                         impute_missing = TRUE,
                                         impute_quantile = 0.01) {
  required_cols <- c(feature_id_cols, sample_cols)
  missing_cols <- setdiff(required_cols, names(final_mat))
  if (length(missing_cols) > 0) {
    stop("final_mat 缺少这些列: ", paste(missing_cols, collapse = ", "))
  }

  annot_cols <- setdiff(names(final_mat), sample_cols)

  annot <- final_mat %>%
    select(all_of(annot_cols)) %>%
    mutate(
      feature_id_raw = do.call(paste, c(across(all_of(feature_id_cols)), sep = "|")),
      feature_id = make.unique(feature_id_raw)
    ) %>%
    relocate(feature_id, feature_id_raw)

  mat_raw <- final_mat %>%
    select(all_of(sample_cols)) %>%
    mutate(across(everything(), ~ suppressWarnings(as.numeric(.)))) %>%
    as.matrix()

  rownames(mat_raw) <- annot$feature_id
  colnames(mat_raw) <- sample_cols

  mat0 <- mat_raw
  mat0[!is.finite(mat0) | mat0 <= 0] <- NA_real_

  if (log2_transform) {
    mat_log2 <- log2(mat0 + add1)
  } else {
    mat_log2 <- mat0
  }

  mat_scaled <- mat_log2
  if (median_scaling) {
    sample_medians <- apply(mat_log2, 2, median, na.rm = TRUE)
    mat_scaled <- sweep(mat_log2, 2, sample_medians, FUN = "-")
  }

  mat_imp <- mat_scaled
  if (impute_missing) {
    fill_val <- apply(mat_scaled, 2, function(v) {
      v2 <- v[is.finite(v)]
      if (length(v2) < 20) {
        if (length(v2) == 0) return(NA_real_)
        return(min(v2, na.rm = TRUE) - 1)
      }
      as.numeric(stats::quantile(v2, probs = impute_quantile, na.rm = TRUE, type = 7))
    })

    for (j in seq_len(ncol(mat_imp))) {
      idx_na <- is.na(mat_imp[, j]) | !is.finite(mat_imp[, j])
      mat_imp[idx_na, j] <- fill_val[j]
    }
  }

  if (!is.null(out_dir)) {
    .safe_dir_create(out_dir)
    write.csv(data.frame(feature_id = rownames(mat_raw), mat_raw, check.names = FALSE),
              file.path(out_dir, "phosphosite_expr_raw.csv"), row.names = FALSE)
    write.csv(data.frame(feature_id = rownames(mat_log2), mat_log2, check.names = FALSE),
              file.path(out_dir, "phosphosite_expr_log2.csv"), row.names = FALSE)
    write.csv(data.frame(feature_id = rownames(mat_scaled), mat_scaled, check.names = FALSE),
              file.path(out_dir, "phosphosite_expr_log2_median_scaled.csv"), row.names = FALSE)
    write.csv(data.frame(feature_id = rownames(mat_imp), mat_imp, check.names = FALSE),
              file.path(out_dir, "phosphosite_expr_log2_imputed.csv"), row.names = FALSE)
    write.csv(annot, file.path(out_dir, "phosphosite_feature_annotation.csv"), row.names = FALSE)
  }

  list(
    expr_raw = mat_raw,
    expr_log2 = mat_log2,
    expr_scaled = mat_scaled,
    expr_imputed = mat_imp,
    feature_annotation = annot
  )
}

# ------------------------------------------------------------
# 4. Read pairwise compare list
# ------------------------------------------------------------
read_pairwise_compare_list <- function(compare_list_file = NULL,
                                       exp_col = NULL,
                                       ctrl_col = NULL,
                                       sheet = 1) {
  if (is.null(compare_list_file)) {
    return(NULL)
  }

  compare_list <- readxl::read_xlsx(compare_list_file, sheet = sheet) %>%
    as.data.frame(check.names = FALSE)

  if (nrow(compare_list) == 0) {
    return(NULL)
  }

  if (is.null(exp_col)) {
    hit_exp <- intersect(names(compare_list), c("实验", "exp", "group1", "treat", "case", "B"))
    if (length(hit_exp) == 0) stop("compare_list 找不到实验组列，可用列名如: 实验/exp/group1/treat。")
    exp_col <- hit_exp[1]
  }

  if (is.null(ctrl_col)) {
    hit_ctrl <- intersect(names(compare_list), c("对照", "ctrl", "group2", "control", "A"))
    if (length(hit_ctrl) == 0) stop("compare_list 找不到对照组列，可用列名如: 对照/ctrl/group2/control。")
    ctrl_col <- hit_ctrl[1]
  }

  compare_list %>%
    transmute(
      exp = .clean_text(.data[[exp_col]]),
      ctrl = .clean_text(.data[[ctrl_col]])
    ) %>%
    filter(!is.na(exp), !is.na(ctrl), exp != "", ctrl != "") %>%
    distinct()
}

make_all_pairwise_compare_list <- function(groups) {
  groups <- unique(as.character(groups))
  groups <- groups[!is.na(groups) & groups != ""]
  if (length(groups) < 2) stop("少于两个分组，无法生成两两比较。")

  pairs <- combn(groups, 2)
  tibble(
    exp = pairs[2, ],
    ctrl = pairs[1, ]
  )
}

# ------------------------------------------------------------
# 5. Single pair phosphosite DE / FC-only analysis
# ------------------------------------------------------------
run_one_phosphosite_de <- function(expr,
                                   feature_annotation,
                                   sample_metadata,
                                   exp_group,
                                   ctrl_group,
                                   group_col = "group",
                                   min_reps_for_limma = 3,
                                   low_rep_strategy = c("group_fc_only", "limma"),
                                   p_type = c("adjp", "pvalue"),
                                   p_thresh = 0.05,
                                   logfc_thresh = 1,
                                   adjust_method = "BH",
                                   out_prefix = NULL,
                                   make_volcano = TRUE,
                                   make_heatmap = TRUE,
                                   save_formats = c("pdf", "png"),
                                   plot_width = 10,
                                   plot_height = 8,
                                   plot_dpi = 300,
                                   heat_show_rownames = FALSE,
                                   heat_show_colnames = FALSE,
                                   cluster_cols = FALSE) {
  low_rep_strategy <- match.arg(low_rep_strategy)
  p_type <- match.arg(tolower(p_type[1]), c("adjp", "pvalue"))
  p_col <- if (p_type == "adjp") "adj.P.Val" else "P.Value"

  sample_metadata <- as.data.frame(sample_metadata, check.names = FALSE)
  if (is.null(rownames(sample_metadata))) {
    rownames(sample_metadata) <- sample_metadata$sample_id
  }

  if (!group_col %in% names(sample_metadata)) {
    stop("sample_metadata 中找不到分组列: ", group_col)
  }

  groups_available <- unique(as.character(sample_metadata[[group_col]]))
  if (!all(c(exp_group, ctrl_group) %in% groups_available)) {
    stop("比较组不在 metadata 中: ", exp_group, " / ", ctrl_group)
  }

  samples_exp <- rownames(sample_metadata)[as.character(sample_metadata[[group_col]]) == exp_group]
  samples_ctrl <- rownames(sample_metadata)[as.character(sample_metadata[[group_col]]) == ctrl_group]
  samples_exp <- intersect(colnames(expr), samples_exp)
  samples_ctrl <- intersect(colnames(expr), samples_ctrl)

  if (length(samples_exp) == 0 || length(samples_ctrl) == 0) {
    stop("比较组没有可用样本: ", exp_group, " n=", length(samples_exp), "; ", ctrl_group, " n=", length(samples_ctrl))
  }

  samples_used <- c(samples_exp, samples_ctrl)
  X <- expr[, samples_used, drop = FALSE]
  meta <- sample_metadata[samples_used, , drop = FALSE]

  use_limma <- length(samples_exp) >= min_reps_for_limma &&
    length(samples_ctrl) >= min_reps_for_limma &&
    ncol(X) > length(unique(meta[[group_col]]))

  if (!use_limma && low_rep_strategy == "limma") {
    use_limma <- TRUE
  }

  comparison_name <- paste0(.safe_slug(exp_group), "_vs_", .safe_slug(ctrl_group))
  method <- if (use_limma) "limma" else "group_FC_only"

  if (use_limma) {
    grp_fac <- factor(as.character(meta[[group_col]]), levels = c(ctrl_group, exp_group))
    grp_safe <- factor(make.names(as.character(grp_fac)), levels = make.names(levels(grp_fac)))
    design <- model.matrix(~ 0 + grp_safe)
    colnames(design) <- levels(grp_safe)

    contrast_str <- paste0(make.names(exp_group), " - ", make.names(ctrl_group))
    cont <- limma::makeContrasts(contrasts = contrast_str, levels = design)

    fit <- limma::lmFit(X, design)
    fit2 <- limma::contrasts.fit(fit, cont)
    fit2 <- limma::eBayes(fit2)

    tt <- limma::topTable(fit2, coef = 1, number = Inf, adjust.method = adjust_method, sort.by = "P")
    if ("B" %in% colnames(tt)) colnames(tt)[colnames(tt) == "B"] <- "B_stat"
    tt$feature_id <- rownames(tt)
  } else {
    exp_stat <- rowMeans(X[, samples_exp, drop = FALSE], na.rm = TRUE)
    ctrl_stat <- rowMeans(X[, samples_ctrl, drop = FALSE], na.rm = TRUE)
    exp_stat[is.nan(exp_stat)] <- NA_real_
    ctrl_stat[is.nan(ctrl_stat)] <- NA_real_

    logFC <- exp_stat - ctrl_stat
    tt <- data.frame(
      feature_id = rownames(X),
      logFC = as.numeric(logFC),
      AveExpr = as.numeric((exp_stat + ctrl_stat) / 2),
      t = NA_real_,
      P.Value = NA_real_,
      adj.P.Val = NA_real_,
      B_stat = NA_real_,
      stringsAsFactors = FALSE
    )
    rownames(tt) <- tt$feature_id
  }

  # Direction: for limma use p + FC; for FC-only use FC only.
  if (use_limma) {
    p_vec <- tt[[p_col]]
    tt$direction <- ifelse(
      !is.na(p_vec) & p_vec < p_thresh & tt$logFC >= logfc_thresh,
      "Up",
      ifelse(!is.na(p_vec) & p_vec < p_thresh & tt$logFC <= -logfc_thresh, "Down", "Not Significant")
    )
  } else {
    tt$direction <- ifelse(
      tt$logFC >= logfc_thresh,
      "Up",
      ifelse(tt$logFC <= -logfc_thresh, "Down", "Not Significant")
    )
  }
  tt$direction <- factor(tt$direction, levels = c("Up", "Not Significant", "Down"))

  tt$comparison <- comparison_name
  tt$exp_group <- exp_group
  tt$ctrl_group <- ctrl_group
  tt$n_exp <- length(samples_exp)
  tt$n_ctrl <- length(samples_ctrl)
  tt$method <- method

  # Add phosphosite annotations. This preserves modified peptide / site IDs.
  res <- feature_annotation %>%
    left_join(tt, by = "feature_id")

  combined <- res %>%
    left_join(
      as.data.frame(X, check.names = FALSE) %>%
        tibble::rownames_to_column("feature_id"),
      by = "feature_id"
    )

  saved_files <- character(0)

  if (!is.null(out_prefix) && nzchar(out_prefix)) {
    .safe_dir_create(dirname(out_prefix))
    f_res <- paste0(out_prefix, "_phosphosite_DE_results.csv")
    f_comb <- paste0(out_prefix, "_combined.csv")
    write.csv(res, f_res, row.names = FALSE, fileEncoding = "GBK")
    write.csv(combined, f_comb, row.names = FALSE, fileEncoding = "GBK")
    saved_files <- c(saved_files, f_res, f_comb)
  }

  # Volcano plot
  volcano_plot <- NULL
  if (isTRUE(make_volcano) && requireNamespace("ggplot2", quietly = TRUE)) {
    volcano_df <- res
    if (use_limma) {
      p_safe <- pmax(volcano_df[[p_col]], .Machine$double.xmin)
      volcano_df$yval <- -log10(p_safe)
      ylab <- paste0("-log10(", p_col, ")")
      hline <- -log10(p_thresh)
    } else {
      volcano_df$yval <- abs(volcano_df$logFC)
      ylab <- "|log2FC| (FC-only)"
      hline <- logfc_thresh
    }

    volcano_plot <- ggplot2::ggplot(volcano_df, ggplot2::aes(x = logFC, y = yval, colour = direction)) +
      ggplot2::geom_point(alpha = 0.45, size = 2.4) +
      ggplot2::scale_color_manual(values = c("Down" = "#67a9cf", "Not Significant" = "#cccccc", "Up" = "#fd8d3c"), drop = TRUE) +
      ggplot2::geom_vline(xintercept = c(-logfc_thresh, logfc_thresh), linetype = 4, color = "black") +
      ggplot2::geom_hline(yintercept = hline, linetype = 4, color = "black") +
      ggplot2::labs(
        x = paste0("log2FC (", exp_group, " - ", ctrl_group, ")"),
        y = ylab,
        color = ""
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(aspect.ratio = 1, legend.position = "right")

    if (!is.null(out_prefix) && nzchar(out_prefix)) {
      for (fmt in tolower(save_formats)) {
        f_plot <- paste0(out_prefix, "_volcano.", fmt)
        ggplot2::ggsave(f_plot, volcano_plot, width = plot_width, height = plot_height, dpi = plot_dpi)
        saved_files <- c(saved_files, f_plot)
      }
    }
  }

  # Heatmap for Up/Down features
  heatmap_plot <- NULL
  heatmap_matrix <- NULL
  heatmap_matrix_row_scaled <- NULL
  if (isTRUE(make_heatmap) && requireNamespace("pheatmap", quietly = TRUE) && requireNamespace("grid", quietly = TRUE)) {
    sig_features <- res %>%
      filter(direction %in% c("Up", "Down")) %>%
      arrange(logFC) %>%
      pull(feature_id)

    sig_features <- intersect(sig_features, rownames(X))

    if (length(sig_features) > 1) {
      heatmap_matrix <- X[sig_features, c(samples_ctrl, samples_exp), drop = FALSE]
      heatmap_matrix_row_scaled <- .scale_rows(heatmap_matrix)

      ann_col <- data.frame(
        Group = factor(c(rep(ctrl_group, length(samples_ctrl)), rep(exp_group, length(samples_exp))),
                       levels = c(ctrl_group, exp_group)),
        row.names = c(samples_ctrl, samples_exp)
      )

      my_palette <- grDevices::colorRampPalette(c("#045a8d", "white", "#d7301f"))(1000)
      heatmap_plot <- pheatmap::pheatmap(
        heatmap_matrix_row_scaled,
        scale = "none",
        show_rownames = isTRUE(heat_show_rownames),
        show_colnames = isTRUE(heat_show_colnames),
        cluster_rows = FALSE,
        cluster_cols = isTRUE(cluster_cols),
        color = my_palette,
        annotation_col = ann_col,
        silent = TRUE
      )

      if (!is.null(out_prefix) && nzchar(out_prefix)) {
        f_raw <- paste0(out_prefix, "_heatmap_matrix_raw.csv")
        f_scaled <- paste0(out_prefix, "_heatmap_matrix_row_scaled.csv")
        write.csv(data.frame(feature_id = rownames(heatmap_matrix), heatmap_matrix, check.names = FALSE), f_raw, row.names = FALSE, fileEncoding = "GBK")
        write.csv(data.frame(feature_id = rownames(heatmap_matrix_row_scaled), heatmap_matrix_row_scaled, check.names = FALSE), f_scaled, row.names = FALSE, fileEncoding = "GBK")

        f_pdf <- paste0(out_prefix, "_heatmap.pdf")
        grDevices::pdf(f_pdf, width = 5, height = 6)
        grid::grid.newpage(); grid::grid.draw(heatmap_plot$gtable)
        grDevices::dev.off()

        f_png <- paste0(out_prefix, "_heatmap.png")
        grDevices::png(f_png, width = 5, height = 6, units = "in", res = 600)
        grid::grid.newpage(); grid::grid.draw(heatmap_plot$gtable)
        grDevices::dev.off()

        saved_files <- c(saved_files, f_raw, f_scaled, f_pdf, f_png)
      }
    }
  }

  list(
    results = res,
    combined = combined,
    summary = table(res$direction, useNA = "ifany"),
    comparison = comparison_name,
    exp_group = exp_group,
    ctrl_group = ctrl_group,
    samples_exp = samples_exp,
    samples_ctrl = samples_ctrl,
    method = method,
    volcano_plot = volcano_plot,
    heatmap_plot = heatmap_plot,
    heatmap_matrix = heatmap_matrix,
    heatmap_matrix_row_scaled = heatmap_matrix_row_scaled,
    saved_files = unique(saved_files)
  )
}

# ------------------------------------------------------------
# 6. Batch phosphosite DE workflow
# ------------------------------------------------------------
run_phosphosite_batch_de <- function(final_mat,
                                     sample_cols,
                                     sampleinfo_file,
                                     samplegroup_file = NULL,
                                     compare_list_file = NULL,
                                     out_dir = "Results/phosphosite_DE",
                                     samplegroup_skip = 10,
                                     sample_id_col = "样品编号",
                                     sample_name_col = "样品信息",
                                     unmatched_group = "ALL",
                                     drop_groups = c("ALL", "QC"),
                                     group_col = "group",
                                     min_reps_for_limma = 3,
                                     low_rep_strategy = c("group_fc_only", "limma"),
                                     p_type = c("adjp", "pvalue"),
                                     p_thresh = 0.05,
                                     logfc_thresh = 1,
                                     adjust_method = "BH",
                                     median_scaling = TRUE,
                                     impute_missing = TRUE,
                                     impute_quantile = 0.01,
                                     make_volcano = TRUE,
                                     make_heatmap = TRUE,
                                     save_formats = c("pdf", "png")) {
  low_rep_strategy <- match.arg(low_rep_strategy)
  p_type <- match.arg(tolower(p_type[1]), c("adjp", "pvalue"))
  .safe_dir_create(out_dir)

  sample_metadata <- prepare_phospho_sample_metadata(
    sampleinfo_file = sampleinfo_file,
    samplegroup_file = samplegroup_file,
    samplegroup_skip = samplegroup_skip,
    sample_id_col = sample_id_col,
    sample_name_col = sample_name_col,
    unmatched_group = unmatched_group,
    out_dir = out_dir
  )

  sample_metadata <- align_phospho_sample_metadata(
    sample_metadata = sample_metadata,
    sample_cols = sample_cols,
    out_dir = out_dir,
    stop_if_unmatched = TRUE
  )

  expr_res <- make_phosphosite_expr_matrix(
    final_mat = final_mat,
    sample_cols = sample_cols,
    out_dir = out_dir,
    median_scaling = median_scaling,
    impute_missing = impute_missing,
    impute_quantile = impute_quantile
  )

  metadata_for_de <- sample_metadata %>%
    filter(!.data[[group_col]] %in% drop_groups)
  rownames(metadata_for_de) <- metadata_for_de$sample_id

  compare_list <- read_pairwise_compare_list(compare_list_file)
  if (is.null(compare_list)) {
    compare_list <- make_all_pairwise_compare_list(unique(metadata_for_de[[group_col]]))
  }

  write.csv(compare_list, file.path(out_dir, "compare_list_used.csv"), row.names = FALSE)
  write.csv(as.data.frame(table(metadata_for_de[[group_col]])), file.path(out_dir, "group_sample_count.csv"), row.names = FALSE)

  result_list <- list()
  for (i in seq_len(nrow(compare_list))) {
    exp_group <- compare_list$exp[i]
    ctrl_group <- compare_list$ctrl[i]
    comp_name <- paste0(.safe_slug(exp_group), "_vs_", .safe_slug(ctrl_group))
    comp_dir <- file.path(out_dir, comp_name)
    .safe_dir_create(comp_dir)

    out_prefix <- file.path(comp_dir, comp_name)

    res_i <- run_one_phosphosite_de(
      expr = expr_res$expr_imputed,
      feature_annotation = expr_res$feature_annotation,
      sample_metadata = metadata_for_de,
      exp_group = exp_group,
      ctrl_group = ctrl_group,
      group_col = group_col,
      min_reps_for_limma = min_reps_for_limma,
      low_rep_strategy = low_rep_strategy,
      p_type = p_type,
      p_thresh = p_thresh,
      logfc_thresh = logfc_thresh,
      adjust_method = adjust_method,
      out_prefix = out_prefix,
      make_volcano = make_volcano,
      make_heatmap = make_heatmap,
      save_formats = save_formats
    )

    result_list[[comp_name]] <- res_i
  }

  all_results <- bind_rows(lapply(result_list, `[[`, "results"))
  write.csv(all_results, file.path(out_dir, "all_pairwise_phosphosite_DE_results.csv"), row.names = FALSE, fileEncoding = "GBK")

  logfc_wide <- all_results %>%
    select(feature_id, comparison, logFC) %>%
    distinct(feature_id, comparison, .keep_all = TRUE) %>%
    pivot_wider(names_from = comparison, values_from = logFC) %>%
    left_join(expr_res$feature_annotation, by = "feature_id") %>%
    relocate(feature_id, feature_id_raw)

  write.csv(logfc_wide, file.path(out_dir, "all_pairwise_log2FC_wide.csv"), row.names = FALSE, fileEncoding = "GBK")

  invisible(list(
    sample_metadata = sample_metadata,
    metadata_for_de = metadata_for_de,
    expr = expr_res,
    compare_list = compare_list,
    result_list = result_list,
    all_results = all_results,
    logfc_wide = logfc_wide
  ))
}

# ============================================================
# Example usage
# ============================================================
# source("01_build_phosphosite_matrix_from_diann.R")
# source("01_build_phosphosite_matrix_from_diann_local_patch.R")
# prep <- prepare_phosphosite_matrix(...)
#
# source("02_prepare_metadata_and_phosphosite_de.R")
# de <- run_phosphosite_batch_de(
#   final_mat = prep$final_mat,
#   sample_cols = prep$sample_cols,
#   sampleinfo_file = "./demo/data/sampleinfo.xlsx",
#   samplegroup_file = "./demo/data/samplegroup.xlsx",
#   compare_list_file = "./demo/data/compare_list.xlsx",
#   out_dir = "./demo/Results/phosphosite_DE",
#   samplegroup_skip = 10,
#   min_reps_for_limma = 3,
#   low_rep_strategy = "group_fc_only",
#   p_thresh = 0.05,
#   logfc_thresh = 1
# )
