# ============================================================
# 03. Rank-based KSEA for phosphosite / phosphopeptide FC results
#
# Purpose:
#   Run kinase enrichment / KSEA-like analysis using phosphosite logFC values
#   generated by 02_prepare_metadata_and_phosphosite_de.R.
#
# Why rank-based KSEA here:
#   In the current demo data, each sample is effectively one group (n = 1).
#   Therefore, step 02 produces logFC but not valid P values/FDR. Rank-based
#   KSEA can still use the ordered logFC vector to infer exploratory kinase
#   activity trends.
#
# Main inputs:
#   de_results : de$all_results from run_phosphosite_batch_de(), or the exported
#                all_pairwise_phosphosite_DE_results.csv / all_pairwise_DE_results.csv
#   site_mat2  : prep$site_mat2 from prepare_phosphosite_matrix(), or exported
#                site_mat2.csv
#
# Main outputs:
#   01_ksea_site_annotation.csv
#   02_ksea_de_results_with_site_label.csv
#   per-comparison KSEA input vectors and enrichment tables
#   per-comparison KSEA signed-score heatmaps/barplots
#   all_rank_based_KSEA_signed_score_long.csv
#   all_rank_based_KSEA_signed_score_wide.csv
#   global kinase signed-score heatmap
#
# Important:
#   This is an exploratory kinase activity inference when there are no biological
#   replicates. Do not interpret the results as statistically validated kinase
#   activity differences.
# ============================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(stringr)
  library(tibble)
})

# ------------------------------------------------------------
# 0. Small utilities
# ------------------------------------------------------------
.safe_dir_create <- function(path) {
  if (!is.null(path) && nzchar(path)) {
    dir.create(path, recursive = TRUE, showWarnings = FALSE)
  }
}

.safe_slug <- function(x) {
  x <- as.character(x)
  x <- gsub("[[:space:]]+", "_", x)
  x <- gsub("[/\\\\:;*?\"<>|]", "_", x)
  x <- gsub("\\+", "plus", x)
  x <- gsub("[^[:alnum:]_.-]", "_", x)
  x <- gsub("_+", "_", x)
  x <- gsub("^_|_$", "", x)
  x
}

.read_table_if_path <- function(x) {
  if (is.character(x) && length(x) == 1 && file.exists(x)) {
    utils::read.csv(x, check.names = FALSE, stringsAsFactors = FALSE)
  } else {
    x
  }
}

.guess_col <- function(df, candidates) {
  hit <- intersect(candidates, colnames(df))
  if (length(hit) == 0) NA_character_ else hit[1]
}

# ------------------------------------------------------------
# 1. Load PhosR kinase-substrate annotation
# ------------------------------------------------------------
load_phosr_kinase_annotation <- function(species = c("mouse", "human")) {
  species <- match.arg(species)

  if (!requireNamespace("PhosR", quietly = TRUE)) {
    stop("需要 PhosR 包。请先安装/加载 PhosR。")
  }

  env <- new.env(parent = emptyenv())
  utils::data("PhosphoSitePlus", package = "PhosR", envir = env)

  obj_name <- if (species == "mouse") "PhosphoSite.mouse" else "PhosphoSite.human"
  if (!exists(obj_name, envir = env, inherits = FALSE)) {
    stop("PhosR::PhosphoSitePlus 中找不到对象: ", obj_name)
  }

  get(obj_name, envir = env, inherits = FALSE)
}

# ------------------------------------------------------------
# 2. Build site annotation matching step 02 feature_id
# ------------------------------------------------------------
build_ksea_site_annotation <- function(site_mat2,
                                       feature_id_cols = c("Protein.Id", "Genes", "Residue.Both", "Modified.Sequence"),
                                       keep_only_single_site = TRUE,
                                       uppercase_gene = TRUE) {
  site_mat2 <- .read_table_if_path(site_mat2)
  site_mat2 <- as.data.frame(site_mat2, check.names = FALSE, stringsAsFactors = FALSE)

  required_cols <- c(feature_id_cols, "abs_pos", "abs_residue")
  missing_cols <- setdiff(required_cols, colnames(site_mat2))
  if (length(missing_cols) > 0) {
    stop("site_mat2 缺少这些列: ", paste(missing_cols, collapse = ", "))
  }

  site_anno <- site_mat2 %>%
    mutate(
      feature_id_raw = do.call(paste, c(across(all_of(feature_id_cols)), sep = "|")),
      feature_id = make.unique(feature_id_raw),
      Residue = as.character(abs_residue),
      Site = suppressWarnings(as.numeric(abs_pos)),
      GeneSymbol = as.character(Genes),
      n_site_in_row = ifelse(
        "Residue.Both" %in% colnames(.),
        stringr::str_count(as.character(Residue.Both), fixed(";")) + 1L,
        1L
      )
    )

  if (uppercase_gene) {
    site_anno <- site_anno %>% mutate(GeneSymbol = toupper(GeneSymbol))
  }

  if (keep_only_single_site) {
    site_anno <- site_anno %>% filter(n_site_in_row == 1L)
  }

  site_anno <- site_anno %>%
    filter(!is.na(Site), !is.na(Residue), Residue %in% c("S", "T", "Y")) %>%
    mutate(site_label = paste0(GeneSymbol, ";", Residue, Site, ";"))

  site_anno %>% distinct(feature_id, .keep_all = TRUE)
}

# ------------------------------------------------------------
# 3. Normalize PhosR pathwayRankBasedEnrichment output
# ------------------------------------------------------------
normalize_ksea_result <- function(enr, comparison, direction) {
  if (is.null(enr)) {
    return(data.frame())
  }

  enr <- as.data.frame(enr, check.names = FALSE, stringsAsFactors = FALSE)
  if (nrow(enr) == 0) {
    return(enr)
  }

  kinase_col <- .guess_col(enr, c("Kinase", "kinase", "Pathway", "pathway", "Name", "name", "Term", "term"))
  if (is.na(kinase_col)) {
    enr$Kinase <- rownames(enr)
  } else if (kinase_col != "Kinase") {
    enr$Kinase <- enr[[kinase_col]]
  }

  p_col <- .guess_col(enr, c("P.Value", "p.value", "pvalue", "p.val", "PValue", "P", "p"))
  padj_col <- .guess_col(enr, c("adj.P.Val", "FDR", "fdr", "p.adjust", "padj", "qvalue", "q.value"))
  score_col <- .guess_col(enr, c("NES", "ES", "EnrichmentScore", "enrichmentScore", "score", "Score", "statistic", "z.score"))

  enr$comparison <- comparison
  enr$ksea_direction <- direction
  enr$p_for_signed_score <- if (!is.na(p_col)) suppressWarnings(as.numeric(enr[[p_col]])) else NA_real_
  enr$padj_for_report <- if (!is.na(padj_col)) suppressWarnings(as.numeric(enr[[padj_col]])) else NA_real_
  enr$score_for_report <- if (!is.na(score_col)) suppressWarnings(as.numeric(enr[[score_col]])) else NA_real_

  enr
}

make_signed_ksea_score <- function(enr_up, enr_down, comparison) {
  up <- normalize_ksea_result(enr_up, comparison = comparison, direction = "UP_or_greater")
  down <- normalize_ksea_result(enr_down, comparison = comparison, direction = "DOWN_or_less")

  if (nrow(up) == 0 && nrow(down) == 0) {
    return(data.frame())
  }

  up2 <- up %>%
    select(Kinase, p_up = p_for_signed_score, padj_up = padj_for_report, score_up = score_for_report)
  down2 <- down %>%
    select(Kinase, p_down = p_for_signed_score, padj_down = padj_for_report, score_down = score_for_report)

  full_join(up2, down2, by = "Kinase") %>%
    mutate(
      comparison = comparison,
      p_up = suppressWarnings(as.numeric(p_up)),
      p_down = suppressWarnings(as.numeric(p_down)),
      p_best = pmin(p_up, p_down, na.rm = TRUE),
      p_best = ifelse(is.infinite(p_best), NA_real_, p_best),
      dominant_direction = case_when(
        is.na(p_up) & is.na(p_down) ~ NA_character_,
        is.na(p_down) ~ "UP_or_greater",
        is.na(p_up) ~ "DOWN_or_less",
        p_up <= p_down ~ "UP_or_greater",
        TRUE ~ "DOWN_or_less"
      ),
      # signed_score > 0: substrates tend to be higher in the numerator group.
      # signed_score < 0: substrates tend to be lower in the numerator group.
      signed_score = case_when(
        is.na(p_best) ~ NA_real_,
        dominant_direction == "UP_or_greater" ~ -log10(pmax(p_best, .Machine$double.xmin)),
        dominant_direction == "DOWN_or_less" ~ log10(pmax(p_best, .Machine$double.xmin)),
        TRUE ~ NA_real_
      )
    ) %>%
    arrange(desc(abs(signed_score)))
}

# ------------------------------------------------------------
# 4. Plot per-comparison KSEA results
# ------------------------------------------------------------
plot_one_ksea_signed_score <- function(signed_score,
                                       comparison,
                                       comp_dir,
                                       top_n = 30,
                                       make_heatmap = TRUE,
                                       make_barplot = TRUE) {
  saved_files <- character(0)

  if (is.null(signed_score) || nrow(signed_score) == 0) {
    return(saved_files)
  }

  plot_df <- signed_score %>%
    filter(!is.na(signed_score), !is.na(Kinase), Kinase != "") %>%
    arrange(desc(abs(signed_score))) %>%
    slice_head(n = top_n) %>%
    mutate(
      Kinase = as.character(Kinase),
      Kinase_plot = factor(Kinase, levels = rev(Kinase)),
      activity_direction = ifelse(signed_score >= 0, "Higher", "Lower")
    )

  if (nrow(plot_df) == 0) {
    return(saved_files)
  }

  comp_slug <- .safe_slug(comparison)

  if (isTRUE(make_barplot) && requireNamespace("ggplot2", quietly = TRUE)) {
    p <- ggplot2::ggplot(plot_df, ggplot2::aes(x = Kinase_plot, y = signed_score, fill = activity_direction)) +
      ggplot2::geom_col(width = 0.75) +
      ggplot2::coord_flip() +
      ggplot2::geom_hline(yintercept = 0, linewidth = 0.3) +
      ggplot2::labs(
        x = NULL,
        y = "Rank-based KSEA signed score",
        fill = "Direction",
        title = comparison
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        plot.title = ggplot2::element_text(hjust = 0.5),
        axis.text.y = ggplot2::element_text(size = 7)
      )

    f_pdf <- file.path(comp_dir, paste0(comp_slug, "_signed_score_barplot.pdf"))
    f_png <- file.path(comp_dir, paste0(comp_slug, "_signed_score_barplot.png"))
    ggplot2::ggsave(f_pdf, p, width = 7, height = max(5, 0.18 * nrow(plot_df) + 2), dpi = 300)
    ggplot2::ggsave(f_png, p, width = 7, height = max(5, 0.18 * nrow(plot_df) + 2), dpi = 300)
    saved_files <- c(saved_files, f_pdf, f_png)
  }

  if (isTRUE(make_heatmap) && requireNamespace("pheatmap", quietly = TRUE)) {
    mat <- as.matrix(plot_df$signed_score)
    rownames(mat) <- plot_df$Kinase
    colnames(mat) <- comparison

    f_pdf <- file.path(comp_dir, paste0(comp_slug, "_signed_score_heatmap.pdf"))
    f_png <- file.path(comp_dir, paste0(comp_slug, "_signed_score_heatmap.png"))

    grDevices::pdf(f_pdf, width = 4.8, height = max(5, 0.16 * nrow(mat) + 2))
    pheatmap::pheatmap(
      mat,
      cluster_rows = FALSE,
      cluster_cols = FALSE,
      fontsize_row = 7,
      fontsize_col = 8,
      main = comparison
    )
    grDevices::dev.off()

    grDevices::png(f_png, width = 4.8, height = max(5, 0.16 * nrow(mat) + 2), units = "in", res = 600)
    pheatmap::pheatmap(
      mat,
      cluster_rows = FALSE,
      cluster_cols = FALSE,
      fontsize_row = 7,
      fontsize_col = 8,
      main = comparison
    )
    grDevices::dev.off()

    saved_files <- c(saved_files, f_pdf, f_png)
  }

  saved_files
}

# ------------------------------------------------------------
# 5. Run one rank-based KSEA comparison
# ------------------------------------------------------------
run_one_rank_based_ksea <- function(stats_tbl,
                                    comparison,
                                    annotation,
                                    out_dir,
                                    min_sites = 10,
                                    make_per_comparison_heatmap = TRUE,
                                    make_per_comparison_barplot = TRUE,
                                    top_n_per_comparison = 30) {
  comp_slug <- .safe_slug(comparison)
  comp_dir <- file.path(out_dir, comp_slug)
  .safe_dir_create(comp_dir)

  stats_tbl <- stats_tbl %>%
    filter(!is.na(logFC), !is.na(site_label), site_label != "") %>%
    group_by(site_label) %>%
    summarise(
      logFC = median(logFC, na.rm = TRUE),
      n_features_collapsed = n(),
      .groups = "drop"
    ) %>%
    arrange(desc(logFC))

  utils::write.csv(stats_tbl, file.path(comp_dir, paste0(comp_slug, "_KSEA_input_logFC_vector.csv")), row.names = FALSE)

  if (nrow(stats_tbl) < min_sites) {
    warning("comparison ", comparison, " 可用于 KSEA 的位点数少于 min_sites=", min_sites, "，跳过。")
    return(list(
      comparison = comparison,
      input_stats = stats_tbl,
      enrichment_up = data.frame(),
      enrichment_down = data.frame(),
      signed_score = data.frame(),
      plot_files = character(0)
    ))
  }

  geneStats <- stats_tbl$logFC
  names(geneStats) <- stats_tbl$site_label
  geneStats <- geneStats[!is.na(geneStats)]

  enr_up <- PhosR::pathwayRankBasedEnrichment(
    geneStats,
    annotation = annotation,
    alter = "greater"
  )

  enr_down <- PhosR::pathwayRankBasedEnrichment(
    geneStats,
    annotation = annotation,
    alter = "less"
  )

  enr_up_n <- normalize_ksea_result(enr_up, comparison = comparison, direction = "UP_or_greater")
  enr_down_n <- normalize_ksea_result(enr_down, comparison = comparison, direction = "DOWN_or_less")
  signed_score <- make_signed_ksea_score(enr_up, enr_down, comparison = comparison)

  utils::write.csv(enr_up_n, file.path(comp_dir, paste0(comp_slug, "_rank_KSEA_UP_greater.csv")), row.names = FALSE)
  utils::write.csv(enr_down_n, file.path(comp_dir, paste0(comp_slug, "_rank_KSEA_DOWN_less.csv")), row.names = FALSE)
  utils::write.csv(signed_score, file.path(comp_dir, paste0(comp_slug, "_rank_KSEA_signed_score.csv")), row.names = FALSE)

  plot_files <- plot_one_ksea_signed_score(
    signed_score = signed_score,
    comparison = comparison,
    comp_dir = comp_dir,
    top_n = top_n_per_comparison,
    make_heatmap = make_per_comparison_heatmap,
    make_barplot = make_per_comparison_barplot
  )

  list(
    comparison = comparison,
    input_stats = stats_tbl,
    enrichment_up = enr_up_n,
    enrichment_down = enr_down_n,
    signed_score = signed_score,
    plot_files = plot_files
  )
}

# ------------------------------------------------------------
# 6. Main wrapper
# ------------------------------------------------------------
run_phosphosite_ksea <- function(de_results,
                                 site_mat2,
                                 out_dir = "Results/phosphosite_KSEA",
                                 species = c("mouse", "human"),
                                 annotation = NULL,
                                 comparison_col = "comparison",
                                 logfc_col = "logFC",
                                 keep_only_single_site = TRUE,
                                 uppercase_gene = TRUE,
                                 min_sites = 10,
                                 make_heatmap = TRUE,
                                 top_n_kinases_heatmap = 80,
                                 make_per_comparison_heatmap = TRUE,
                                 make_per_comparison_barplot = TRUE,
                                 top_n_per_comparison = 30) {
  species <- match.arg(species)
  .safe_dir_create(out_dir)

  if (!requireNamespace("PhosR", quietly = TRUE)) {
    stop("需要 PhosR 包。请先安装/加载 PhosR。")
  }

  de_results <- .read_table_if_path(de_results)
  de_results <- as.data.frame(de_results, check.names = FALSE, stringsAsFactors = FALSE)

  if (!comparison_col %in% colnames(de_results)) {
    stop("de_results 缺少 comparison 列: ", comparison_col)
  }
  if (!logfc_col %in% colnames(de_results)) {
    stop("de_results 缺少 logFC 列: ", logfc_col)
  }
  if (!"feature_id" %in% colnames(de_results)) {
    stop("de_results 缺少 feature_id 列。请使用第二步脚本输出的 all_results。")
  }

  site_anno <- build_ksea_site_annotation(
    site_mat2 = site_mat2,
    keep_only_single_site = keep_only_single_site,
    uppercase_gene = uppercase_gene
  )

  utils::write.csv(site_anno, file.path(out_dir, "01_ksea_site_annotation.csv"), row.names = FALSE)

  if (is.null(annotation)) {
    annotation <- load_phosr_kinase_annotation(species = species)
  }

  de2 <- de_results %>%
    mutate(logFC = suppressWarnings(as.numeric(.data[[logfc_col]]))) %>%
    left_join(site_anno %>% select(feature_id, site_label, GeneSymbol, Residue, Site), by = "feature_id")

  utils::write.csv(de2, file.path(out_dir, "02_ksea_de_results_with_site_label.csv"), row.names = FALSE)

  match_summary <- data.frame(
    total_de_rows = nrow(de2),
    rows_with_site_label = sum(!is.na(de2$site_label) & de2$site_label != ""),
    rows_without_site_label = sum(is.na(de2$site_label) | de2$site_label == ""),
    unique_site_labels = length(unique(de2$site_label[!is.na(de2$site_label) & de2$site_label != ""])),
    stringsAsFactors = FALSE
  )
  utils::write.csv(match_summary, file.path(out_dir, "02_ksea_site_label_match_summary.csv"), row.names = FALSE)

  comparisons <- unique(as.character(de2[[comparison_col]]))
  comparisons <- comparisons[!is.na(comparisons) & comparisons != ""]

  if (length(comparisons) == 0) {
    stop("de_results 中没有可用 comparison。")
  }

  result_list <- list()
  for (cn in comparisons) {
    stats_tbl <- de2 %>%
      filter(.data[[comparison_col]] == cn) %>%
      select(feature_id, site_label, logFC, GeneSymbol, Residue, Site)

    result_list[[cn]] <- run_one_rank_based_ksea(
      stats_tbl = stats_tbl,
      comparison = cn,
      annotation = annotation,
      out_dir = out_dir,
      min_sites = min_sites,
      make_per_comparison_heatmap = make_per_comparison_heatmap,
      make_per_comparison_barplot = make_per_comparison_barplot,
      top_n_per_comparison = top_n_per_comparison
    )
  }

  signed_long <- bind_rows(lapply(result_list, `[[`, "signed_score"))
  utils::write.csv(signed_long, file.path(out_dir, "all_rank_based_KSEA_signed_score_long.csv"), row.names = FALSE)

  plot_files <- unlist(lapply(result_list, `[[`, "plot_files"), use.names = FALSE)
  utils::write.csv(
    data.frame(plot_file = unique(plot_files), stringsAsFactors = FALSE),
    file.path(out_dir, "per_comparison_plot_files.csv"),
    row.names = FALSE
  )

  if (nrow(signed_long) > 0) {
    signed_wide <- signed_long %>%
      select(Kinase, comparison, signed_score) %>%
      distinct(Kinase, comparison, .keep_all = TRUE) %>%
      pivot_wider(names_from = comparison, values_from = signed_score)

    utils::write.csv(signed_wide, file.path(out_dir, "all_rank_based_KSEA_signed_score_wide.csv"), row.names = FALSE)

    if (isTRUE(make_heatmap) && requireNamespace("pheatmap", quietly = TRUE)) {
      mat <- signed_wide %>%
        tibble::column_to_rownames("Kinase") %>%
        as.matrix()

      mat <- mat[rowSums(!is.na(mat)) > 0, , drop = FALSE]

      if (nrow(mat) > 1 && ncol(mat) > 0) {
        max_abs <- apply(abs(mat), 1, max, na.rm = TRUE)
        max_abs[!is.finite(max_abs)] <- NA_real_
        keep <- order(max_abs, decreasing = TRUE, na.last = NA)
        keep <- keep[seq_len(min(length(keep), top_n_kinases_heatmap))]
        mat_plot <- mat[keep, , drop = FALSE]

        pdf(file.path(out_dir, "all_rank_based_KSEA_signed_score_heatmap.pdf"), width = 10, height = 10)
        pheatmap::pheatmap(mat_plot, fontsize_row = 6, fontsize_col = 8, main = "Rank-based KSEA signed score")
        grDevices::dev.off()

        png(file.path(out_dir, "all_rank_based_KSEA_signed_score_heatmap.png"), width = 10, height = 10, units = "in", res = 600)
        pheatmap::pheatmap(mat_plot, fontsize_row = 6, fontsize_col = 8, main = "Rank-based KSEA signed score")
        grDevices::dev.off()
      }
    }
  } else {
    signed_wide <- data.frame()
  }

  saveRDS(result_list, file.path(out_dir, "rank_based_KSEA_result_list.rds"))

  invisible(list(
    site_annotation = site_anno,
    de_results_with_site_label = de2,
    match_summary = match_summary,
    result_list = result_list,
    signed_long = signed_long,
    signed_wide = signed_wide,
    per_comparison_plot_files = unique(plot_files),
    annotation = annotation
  ))
}

# ============================================================
# Example usage
# ============================================================
# source("03_run_phosphosite_ksea.R")
#
# ksea <- run_phosphosite_ksea(
#   de_results = de$all_results,
#   site_mat2 = prep$site_mat2,
#   out_dir = "./demo/Results/phosphosite_KSEA",
#   species = "mouse",
#   keep_only_single_site = TRUE,
#   min_sites = 10,
#   make_per_comparison_heatmap = TRUE,
#   make_per_comparison_barplot = TRUE,
#   top_n_per_comparison = 30
# )
#
# # Or use exported CSV files:
# ksea <- run_phosphosite_ksea(
#   de_results = "./demo/Results/phosphosite_DE/all_pairwise_phosphosite_DE_results.csv",
#   site_mat2 = "./demo/Results/prepare_phosphosite_matrix/site_mat2.csv",
#   out_dir = "./demo/Results/phosphosite_KSEA",
#   species = "mouse"
# )
