# ============================================================
# 03. Rank-based KSEA for phosphosite / phosphopeptide FC results
#
# Purpose:
#   Run kinase enrichment / KSEA-like analysis using phosphosite logFC values
#   generated by 02_prepare_metadata_and_phosphosite_de.R.
#
# Why this implementation was changed:
#   The previous version called PhosR::pathwayRankBasedEnrichment() directly and
#   then guessed which returned column or row name represented the kinase. In
#   practice, this can mislabel non-kinase names as Kinase. For example, names
#   such as "Yang" may come from the internal annotation/result metadata rather
#   than from the user's input data.
#
#   This version therefore does NOT guess kinase names from the enrichment output.
#   Instead, it explicitly converts PhosR's kinase-substrate annotation into a
#   two-column table:
#       Kinase | site_label
#   and then computes rank-based kinase scores from that explicit annotation.
#
# Important for single-sample designs:
#   If each sample is one group, step 02 only provides logFC and not valid P/FDR.
#   The KSEA results here should be interpreted as exploratory kinase activity
#   trends based on phosphosite logFC ranking.
# ============================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(stringr)
  library(tibble)
})

# ------------------------------------------------------------
# 0. Small utilities
# ------------------------------------------------------------
.safe_dir_create <- function(path) {
  if (!is.null(path) && nzchar(path)) {
    dir.create(path, recursive = TRUE, showWarnings = FALSE)
  }
}

.safe_slug <- function(x) {
  x <- as.character(x)
  x <- gsub("[[:space:]]+", "_", x)
  x <- gsub("[/\\\\:;*?\"<>|]", "_", x)
  x <- gsub("\\+", "plus", x)
  x <- gsub("[^[:alnum:]_.-]", "_", x)
  x <- gsub("_+", "_", x)
  x <- gsub("^_|_$", "", x)
  x
}

.read_table_if_path <- function(x) {
  if (is.character(x) && length(x) == 1 && file.exists(x)) {
    utils::read.csv(x, check.names = FALSE, stringsAsFactors = FALSE)
  } else {
    x
  }
}

.guess_col <- function(df, candidates) {
  hit <- intersect(candidates, colnames(df))
  if (length(hit) == 0) NA_character_ else hit[1]
}

.safe_wilcox_p <- function(x, y, alternative) {
  x <- x[is.finite(x)]
  y <- y[is.finite(y)]
  if (length(x) == 0 || length(y) == 0) return(NA_real_)
  out <- tryCatch(
    stats::wilcox.test(x, y, alternative = alternative, exact = FALSE)$p.value,
    error = function(e) NA_real_,
    warning = function(w) suppressWarnings(stats::wilcox.test(x, y, alternative = alternative, exact = FALSE)$p.value)
  )
  as.numeric(out)
}

# ------------------------------------------------------------
# 1. Load and normalize kinase-substrate annotation
# ------------------------------------------------------------
load_phosr_kinase_annotation <- function(species = c("mouse", "human")) {
  species <- match.arg(species)

  if (!requireNamespace("PhosR", quietly = TRUE)) {
    stop("需要 PhosR 包。请先安装/加载 PhosR。")
  }

  env <- new.env(parent = emptyenv())
  utils::data("PhosphoSitePlus", package = "PhosR", envir = env)

  obj_name <- if (species == "mouse") "PhosphoSite.mouse" else "PhosphoSite.human"
  if (!exists(obj_name, envir = env, inherits = FALSE)) {
    stop("PhosR::PhosphoSitePlus 中找不到对象: ", obj_name)
  }

  get(obj_name, envir = env, inherits = FALSE)
}

normalize_kinase_annotation <- function(annotation) {
  # Case 1: list, usually named by kinase, each element is a vector of sites.
  if (is.list(annotation) && !is.data.frame(annotation)) {
    kinase_names <- names(annotation)
    if (is.null(kinase_names)) {
      stop("annotation 是 list，但没有 names；无法确定 kinase 名称。")
    }

    anno_tbl <- tibble::tibble(
      Kinase = rep(kinase_names, lengths(annotation)),
      site_label = as.character(unlist(annotation, use.names = FALSE))
    )
  } else {
    # Case 2: data.frame-like annotation.
    anno_df <- as.data.frame(annotation, check.names = FALSE, stringsAsFactors = FALSE)
    kinase_col <- .guess_col(anno_df, c("Kinase", "kinase", "Kinase.Gene", "KinaseGene", "enzyme", "Enzyme"))
    site_col <- .guess_col(anno_df, c("site_label", "Site", "site", "Substrate", "substrate", "Residue.Both"))

    if (is.na(kinase_col) || is.na(site_col)) {
      stop("annotation data.frame 需要能识别 Kinase 和 site_label/Site 列。当前列：", paste(colnames(anno_df), collapse = ", "))
    }

    anno_tbl <- anno_df %>%
      transmute(
        Kinase = as.character(.data[[kinase_col]]),
        site_label = as.character(.data[[site_col]])
      )
  }

  anno_tbl %>%
    mutate(
      Kinase = trimws(as.character(Kinase)),
      site_label = trimws(as.character(site_label))
    ) %>%
    filter(!is.na(Kinase), Kinase != "", !is.na(site_label), site_label != "") %>%
    distinct(Kinase, site_label)
}

# ------------------------------------------------------------
# 2. Build site annotation matching step 02 feature_id
# ------------------------------------------------------------
build_ksea_site_annotation <- function(site_mat2,
                                       feature_id_cols = c("Protein.Id", "Genes", "Residue.Both", "Modified.Sequence"),
                                       keep_only_single_site = TRUE,
                                       uppercase_gene = TRUE) {
  site_mat2 <- .read_table_if_path(site_mat2)
  site_mat2 <- as.data.frame(site_mat2, check.names = FALSE, stringsAsFactors = FALSE)

  required_cols <- c(feature_id_cols, "abs_pos", "abs_residue")
  missing_cols <- setdiff(required_cols, colnames(site_mat2))
  if (length(missing_cols) > 0) {
    stop("site_mat2 缺少这些列: ", paste(missing_cols, collapse = ", "))
  }

  site_anno <- site_mat2 %>%
    mutate(
      feature_id_raw = do.call(paste, c(across(all_of(feature_id_cols)), sep = "|")),
      feature_id = make.unique(feature_id_raw),
      Residue = as.character(abs_residue),
      Site = suppressWarnings(as.numeric(abs_pos)),
      GeneSymbol = as.character(Genes),
      n_site_in_row = ifelse(
        "Residue.Both" %in% colnames(.),
        stringr::str_count(as.character(Residue.Both), fixed(";")) + 1L,
        1L
      )
    )

  if (uppercase_gene) {
    site_anno <- site_anno %>% mutate(GeneSymbol = toupper(GeneSymbol))
  }

  if (keep_only_single_site) {
    site_anno <- site_anno %>% filter(n_site_in_row == 1L)
  }

  site_anno <- site_anno %>%
    filter(!is.na(Site), !is.na(Residue), Residue %in% c("S", "T", "Y")) %>%
    mutate(site_label = paste0(GeneSymbol, ";", Residue, Site, ";"))

  site_anno %>% distinct(feature_id, .keep_all = TRUE)
}

# ------------------------------------------------------------
# 3. Explicit rank-based KSEA calculation
# ------------------------------------------------------------
calculate_rank_based_ksea <- function(geneStats,
                                      annotation_tbl,
                                      min_substrates = 1,
                                      min_background = 20) {
  geneStats <- geneStats[is.finite(geneStats)]
  geneStats <- geneStats[!is.na(names(geneStats)) & names(geneStats) != ""]

  if (length(geneStats) == 0) {
    return(data.frame())
  }

  kinase_list <- split(annotation_tbl$site_label, annotation_tbl$Kinase)

  res_list <- lapply(names(kinase_list), function(kinase) {
    kinase_sites <- unique(as.character(kinase_list[[kinase]]))
    hit_sites <- intersect(kinase_sites, names(geneStats))
    bg_sites <- setdiff(names(geneStats), hit_sites)

    if (length(hit_sites) < min_substrates || length(bg_sites) < min_background) {
      return(NULL)
    }

    sub_stats <- geneStats[hit_sites]
    bg_stats <- geneStats[bg_sites]

    p_up <- .safe_wilcox_p(sub_stats, bg_stats, alternative = "greater")
    p_down <- .safe_wilcox_p(sub_stats, bg_stats, alternative = "less")

    p_best <- suppressWarnings(min(c(p_up, p_down), na.rm = TRUE))
    if (!is.finite(p_best)) p_best <- NA_real_

    dominant_direction <- dplyr::case_when(
      is.na(p_up) & is.na(p_down) ~ NA_character_,
      is.na(p_down) ~ "UP_or_greater",
      is.na(p_up) ~ "DOWN_or_less",
      p_up <= p_down ~ "UP_or_greater",
      TRUE ~ "DOWN_or_less"
    )

    signed_score <- dplyr::case_when(
      is.na(p_best) ~ NA_real_,
      dominant_direction == "UP_or_greater" ~ -log10(pmax(p_best, .Machine$double.xmin)),
      dominant_direction == "DOWN_or_less" ~ log10(pmax(p_best, .Machine$double.xmin)),
      TRUE ~ NA_real_
    )

    data.frame(
      Kinase = kinase,
      n_substrates = length(hit_sites),
      mean_logFC_substrates = mean(sub_stats, na.rm = TRUE),
      median_logFC_substrates = stats::median(sub_stats, na.rm = TRUE),
      mean_logFC_background = mean(bg_stats, na.rm = TRUE),
      p_up = p_up,
      p_down = p_down,
      p_best = p_best,
      dominant_direction = dominant_direction,
      signed_score = signed_score,
      matched_sites = paste(hit_sites, collapse = ";"),
      stringsAsFactors = FALSE
    )
  })

  res <- bind_rows(res_list)
  if (nrow(res) == 0) return(res)

  res %>%
    mutate(
      padj_up = p.adjust(p_up, method = "BH"),
      padj_down = p.adjust(p_down, method = "BH"),
      padj_best = p.adjust(p_best, method = "BH")
    ) %>%
    arrange(desc(abs(signed_score)))
}

# ------------------------------------------------------------
# 4. Plot per-comparison KSEA results
# ------------------------------------------------------------
plot_one_ksea_signed_score <- function(signed_score,
                                       comparison,
                                       comp_dir,
                                       top_n = 30,
                                       make_heatmap = TRUE,
                                       make_barplot = TRUE) {
  saved_files <- character(0)

  if (is.null(signed_score) || nrow(signed_score) == 0) {
    return(saved_files)
  }

  plot_df <- signed_score %>%
    filter(!is.na(signed_score), !is.na(Kinase), Kinase != "") %>%
    arrange(desc(abs(signed_score))) %>%
    slice_head(n = top_n) %>%
    mutate(
      Kinase = as.character(Kinase),
      Kinase_plot = factor(Kinase, levels = rev(Kinase)),
      activity_direction = ifelse(signed_score >= 0, "Higher", "Lower")
    )

  if (nrow(plot_df) == 0) {
    return(saved_files)
  }

  comp_slug <- .safe_slug(comparison)

  if (isTRUE(make_barplot) && requireNamespace("ggplot2", quietly = TRUE)) {
    p <- ggplot2::ggplot(plot_df, ggplot2::aes(x = Kinase_plot, y = signed_score, fill = activity_direction)) +
      ggplot2::geom_col(width = 0.75) +
      ggplot2::coord_flip() +
      ggplot2::geom_hline(yintercept = 0, linewidth = 0.3) +
      ggplot2::labs(
        x = NULL,
        y = "Rank-based KSEA signed score",
        fill = "Direction",
        title = comparison
      ) +
      ggplot2::theme_bw() +
      ggplot2::theme(
        plot.title = ggplot2::element_text(hjust = 0.5),
        axis.text.y = ggplot2::element_text(size = 7)
      )

    f_pdf <- file.path(comp_dir, paste0(comp_slug, "_signed_score_barplot.pdf"))
    f_png <- file.path(comp_dir, paste0(comp_slug, "_signed_score_barplot.png"))
    ggplot2::ggsave(f_pdf, p, width = 7, height = max(5, 0.18 * nrow(plot_df) + 2), dpi = 300)
    ggplot2::ggsave(f_png, p, width = 7, height = max(5, 0.18 * nrow(plot_df) + 2), dpi = 300)
    saved_files <- c(saved_files, f_pdf, f_png)
  }

  if (isTRUE(make_heatmap) && requireNamespace("pheatmap", quietly = TRUE)) {
    mat <- as.matrix(plot_df$signed_score)
    rownames(mat) <- plot_df$Kinase
    colnames(mat) <- comparison

    f_pdf <- file.path(comp_dir, paste0(comp_slug, "_signed_score_heatmap.pdf"))
    f_png <- file.path(comp_dir, paste0(comp_slug, "_signed_score_heatmap.png"))

    grDevices::pdf(f_pdf, width = 4.8, height = max(5, 0.16 * nrow(mat) + 2))
    pheatmap::pheatmap(mat, cluster_rows = FALSE, cluster_cols = FALSE, fontsize_row = 7, fontsize_col = 8, main = comparison)
    grDevices::dev.off()

    grDevices::png(f_png, width = 4.8, height = max(5, 0.16 * nrow(mat) + 2), units = "in", res = 600)
    pheatmap::pheatmap(mat, cluster_rows = FALSE, cluster_cols = FALSE, fontsize_row = 7, fontsize_col = 8, main = comparison)
    grDevices::dev.off()

    saved_files <- c(saved_files, f_pdf, f_png)
  }

  saved_files
}

# ------------------------------------------------------------
# 5. Run one rank-based KSEA comparison
# ------------------------------------------------------------
run_one_rank_based_ksea <- function(stats_tbl,
                                    comparison,
                                    annotation_tbl,
                                    out_dir,
                                    min_sites = 10,
                                    min_substrates = 1,
                                    min_background = 20,
                                    make_per_comparison_heatmap = TRUE,
                                    make_per_comparison_barplot = TRUE,
                                    top_n_per_comparison = 30) {
  comp_slug <- .safe_slug(comparison)
  comp_dir <- file.path(out_dir, comp_slug)
  .safe_dir_create(comp_dir)

  stats_tbl <- stats_tbl %>%
    filter(!is.na(logFC), !is.na(site_label), site_label != "") %>%
    group_by(site_label) %>%
    summarise(
      logFC = median(logFC, na.rm = TRUE),
      n_features_collapsed = n(),
      .groups = "drop"
    ) %>%
    arrange(desc(logFC))

  utils::write.csv(stats_tbl, file.path(comp_dir, paste0(comp_slug, "_KSEA_input_logFC_vector.csv")), row.names = FALSE)

  if (nrow(stats_tbl) < min_sites) {
    warning("comparison ", comparison, " 可用于 KSEA 的位点数少于 min_sites=", min_sites, "，跳过。")
    return(list(
      comparison = comparison,
      input_stats = stats_tbl,
      signed_score = data.frame(),
      plot_files = character(0)
    ))
  }

  geneStats <- stats_tbl$logFC
  names(geneStats) <- stats_tbl$site_label
  geneStats <- geneStats[!is.na(geneStats)]

  signed_score <- calculate_rank_based_ksea(
    geneStats = geneStats,
    annotation_tbl = annotation_tbl,
    min_substrates = min_substrates,
    min_background = min_background
  ) %>%
    mutate(comparison = comparison, .before = 1)

  utils::write.csv(signed_score, file.path(comp_dir, paste0(comp_slug, "_rank_KSEA_signed_score.csv")), row.names = FALSE)

  plot_files <- plot_one_ksea_signed_score(
    signed_score = signed_score,
    comparison = comparison,
    comp_dir = comp_dir,
    top_n = top_n_per_comparison,
    make_heatmap = make_per_comparison_heatmap,
    make_barplot = make_per_comparison_barplot
  )

  list(
    comparison = comparison,
    input_stats = stats_tbl,
    signed_score = signed_score,
    plot_files = plot_files
  )
}

# ------------------------------------------------------------
# 6. Main wrapper
# ------------------------------------------------------------
run_phosphosite_ksea <- function(de_results,
                                 site_mat2,
                                 out_dir = "Results/phosphosite_KSEA",
                                 species = c("mouse", "human"),
                                 annotation = NULL,
                                 comparison_col = "comparison",
                                 logfc_col = "logFC",
                                 keep_only_single_site = TRUE,
                                 uppercase_gene = TRUE,
                                 min_sites = 10,
                                 min_substrates = 1,
                                 min_background = 20,
                                 make_heatmap = TRUE,
                                 top_n_kinases_heatmap = 80,
                                 make_per_comparison_heatmap = TRUE,
                                 make_per_comparison_barplot = TRUE,
                                 top_n_per_comparison = 30) {
  species <- match.arg(species)
  .safe_dir_create(out_dir)

  de_results <- .read_table_if_path(de_results)
  de_results <- as.data.frame(de_results, check.names = FALSE, stringsAsFactors = FALSE)

  if (!comparison_col %in% colnames(de_results)) {
    stop("de_results 缺少 comparison 列: ", comparison_col)
  }
  if (!logfc_col %in% colnames(de_results)) {
    stop("de_results 缺少 logFC 列: ", logfc_col)
  }
  if (!"feature_id" %in% colnames(de_results)) {
    stop("de_results 缺少 feature_id 列。请使用第二步脚本输出的 all_results。")
  }

  site_anno <- build_ksea_site_annotation(
    site_mat2 = site_mat2,
    keep_only_single_site = keep_only_single_site,
    uppercase_gene = uppercase_gene
  )

  utils::write.csv(site_anno, file.path(out_dir, "01_ksea_site_annotation.csv"), row.names = FALSE)

  if (is.null(annotation)) {
    annotation <- load_phosr_kinase_annotation(species = species)
  }

  annotation_tbl <- normalize_kinase_annotation(annotation)
  utils::write.csv(annotation_tbl, file.path(out_dir, "00_ksea_kinase_substrate_annotation_used.csv"), row.names = FALSE)

  # Diagnostic file: if strange names appear in Kinase, check this file first.
  kinase_name_check <- annotation_tbl %>%
    count(Kinase, name = "n_substrate_sites") %>%
    arrange(Kinase)
  utils::write.csv(kinase_name_check, file.path(out_dir, "00_ksea_kinase_names_used.csv"), row.names = FALSE)

  de2 <- de_results %>%
    mutate(logFC = suppressWarnings(as.numeric(.data[[logfc_col]]))) %>%
    left_join(site_anno %>% select(feature_id, site_label, GeneSymbol, Residue, Site), by = "feature_id")

  utils::write.csv(de2, file.path(out_dir, "02_ksea_de_results_with_site_label.csv"), row.names = FALSE)

  match_summary <- data.frame(
    total_de_rows = nrow(de2),
    rows_with_site_label = sum(!is.na(de2$site_label) & de2$site_label != ""),
    rows_without_site_label = sum(is.na(de2$site_label) | de2$site_label == ""),
    unique_site_labels = length(unique(de2$site_label[!is.na(de2$site_label) & de2$site_label != ""])),
    stringsAsFactors = FALSE
  )
  utils::write.csv(match_summary, file.path(out_dir, "02_ksea_site_label_match_summary.csv"), row.names = FALSE)

  comparisons <- unique(as.character(de2[[comparison_col]]))
  comparisons <- comparisons[!is.na(comparisons) & comparisons != ""]

  if (length(comparisons) == 0) {
    stop("de_results 中没有可用 comparison。")
  }

  result_list <- list()
  for (cn in comparisons) {
    stats_tbl <- de2 %>%
      filter(.data[[comparison_col]] == cn) %>%
      select(feature_id, site_label, logFC, GeneSymbol, Residue, Site)

    result_list[[cn]] <- run_one_rank_based_ksea(
      stats_tbl = stats_tbl,
      comparison = cn,
      annotation_tbl = annotation_tbl,
      out_dir = out_dir,
      min_sites = min_sites,
      min_substrates = min_substrates,
      min_background = min_background,
      make_per_comparison_heatmap = make_per_comparison_heatmap,
      make_per_comparison_barplot = make_per_comparison_barplot,
      top_n_per_comparison = top_n_per_comparison
    )
  }

  signed_long <- bind_rows(lapply(result_list, `[[`, "signed_score"))
  utils::write.csv(signed_long, file.path(out_dir, "all_rank_based_KSEA_signed_score_long.csv"), row.names = FALSE)

  plot_files <- unlist(lapply(result_list, `[[`, "plot_files"), use.names = FALSE)
  utils::write.csv(
    data.frame(plot_file = unique(plot_files), stringsAsFactors = FALSE),
    file.path(out_dir, "per_comparison_plot_files.csv"),
    row.names = FALSE
  )

  if (nrow(signed_long) > 0) {
    signed_wide <- signed_long %>%
      select(Kinase, comparison, signed_score) %>%
      distinct(Kinase, comparison, .keep_all = TRUE) %>%
      pivot_wider(names_from = comparison, values_from = signed_score)

    utils::write.csv(signed_wide, file.path(out_dir, "all_rank_based_KSEA_signed_score_wide.csv"), row.names = FALSE)

    if (isTRUE(make_heatmap) && requireNamespace("pheatmap", quietly = TRUE)) {
      mat <- signed_wide %>%
        tibble::column_to_rownames("Kinase") %>%
        as.matrix()

      mat <- mat[rowSums(!is.na(mat)) > 0, , drop = FALSE]

      if (nrow(mat) > 1 && ncol(mat) > 0) {
        max_abs <- apply(abs(mat), 1, max, na.rm = TRUE)
        max_abs[!is.finite(max_abs)] <- NA_real_
        keep <- order(max_abs, decreasing = TRUE, na.last = NA)
        keep <- keep[seq_len(min(length(keep), top_n_kinases_heatmap))]
        mat_plot <- mat[keep, , drop = FALSE]

        pdf(file.path(out_dir, "all_rank_based_KSEA_signed_score_heatmap.pdf"), width = 10, height = 10)
        pheatmap::pheatmap(mat_plot, fontsize_row = 6, fontsize_col = 8, main = "Rank-based KSEA signed score")
        grDevices::dev.off()

        png(file.path(out_dir, "all_rank_based_KSEA_signed_score_heatmap.png"), width = 10, height = 10, units = "in", res = 600)
        pheatmap::pheatmap(mat_plot, fontsize_row = 6, fontsize_col = 8, main = "Rank-based KSEA signed score")
        grDevices::dev.off()
      }
    }
  } else {
    signed_wide <- data.frame()
  }

  saveRDS(result_list, file.path(out_dir, "rank_based_KSEA_result_list.rds"))

  invisible(list(
    site_annotation = site_anno,
    annotation_tbl = annotation_tbl,
    kinase_name_check = kinase_name_check,
    de_results_with_site_label = de2,
    match_summary = match_summary,
    result_list = result_list,
    signed_long = signed_long,
    signed_wide = signed_wide,
    per_comparison_plot_files = unique(plot_files),
    annotation = annotation
  ))
}

# ============================================================
# Example usage
# ============================================================
# source("03_run_phosphosite_ksea.R")
#
# ksea <- run_phosphosite_ksea(
#   de_results = de$all_results,
#   site_mat2 = prep$site_mat2,
#   out_dir = "./demo/Results/phosphosite_KSEA",
#   species = "mouse",
#   keep_only_single_site = TRUE,
#   min_sites = 10,
#   min_substrates = 1,
#   make_per_comparison_heatmap = TRUE,
#   make_per_comparison_barplot = TRUE,
#   top_n_per_comparison = 30
# )
